web_day7_rev/urls.py
from django.urls import path
from . import views

app_name = 'mtv'

urlpatterns = [
    # mtv/ - home
    path('', views.index, name='index'),
    # mtv/pk번호/ - 상세 페이지
    path('<int:article_pk>/', views.detail, name='detail'),
    # mtv/new/ - 새로운 글 생성을 위한 페이지
    path('new/', views.new, name='new'),
    # mtv/create/ - 새로운 글을 생성하는 업무 자체를 하는 곳
    path('create/', views.create, name='create'),
    # mtv/pk번호/edit/ - 기존의 글 수정/삭제를 위한 페이지
    path('<int:article_pk>/edit/', views.edit, name='edit'),
    # mtv/pk번호/update/ - 기존의 글 수정 업무 자체를 하는 곳
    path('<int:article_pk>/update/', views.update, name='update'),
    # mtv/pk번호/delete/ - 기존의 글 삭제하는 곳
    path('<int:article_pk>/delete/', views.delete, name='delete'),
]

web_day7_rev/models.py
from django.db import models

class Article(models.Model):
    subject = models.CharField(max_length=100)
    description = models.TextField()

web_day7_rev/views.py
from django.shortcuts import render, redirect
from .models import Article


def index(request):
    # home - 전체 목록을 다 볼 수 있어야 함
    articles = Article.objects.all()
    content = {'articles':articles, }
    return render(request, 'mtv/index.html', content)

def detail(request, article_pk):
    # detail - 한 개의 pk 번호의 상세 목록을 볼 수 있어야 함
    article = Article.objects.get(pk=article_pk)
    content = {'article': article,}
    return render(request, 'mtv/detail.html', content)

def new(request):
    # new - 새로운 글 작성을 위한 페이지로 이동이 필요함
    return render(request, 'mtv/new.html')

def create(request):
    # create - 새로운 글 작성을 위한 작업 함수 
    # 새로운 글 작성을 위해선 새로운 객체 생성 필요
    # 각 db column에 맞게 request해서 데이터를 받아옴 
    # 객체 저장
    # 작성이 끝났으면 작성된 내용이 무엇인지 볼 수 있는 detail 페이지로 이동
    article = Article()
    article.subject = request.POST['subject']
    article.description =request.POST['description']
    article.save()
    return redirect('mtv:detail', article.pk)

def edit(request, article_pk):
    # edit - 기존의 글 수정/삭제 하는 페이지로 이동
    # 이동을 위해선 기존 페이지 선택이 필요
    article = Article.objects.get(pk=article_pk)
    content = {'article': article,}
    return render(request, 'mtv/edit.html', content)

def update(request, article_pk):
    # update - 기존의 글 수정을 위한 작업 함수 
    # 기존의 글 수정을 위해선 기존 페이지 선택 필요
    # 각 db column에 맞게 수정 데이터들을 request해서 데이터를 받아옴
    # 객체 저장
    # 수정이 끝났으면 수정된 내용이 무엇인지 볼 수 있는 detail 페이지로 이동
    article = Article.objects.get(pk=article_pk)
    article.subject = request.POST['subject']
    article.description = request.POST['description']
    article.save()
    return redirect('mtv:detail', article.pk)

def delete(request, article_pk):
    # delete - 기존의 글 삭제를 위한 작업 함수
    # request를 POST로 한 경우에만 진행
    # 기존의 글 삭제를 위해 페이지 선택 필요
    # 삭제가 완료된 목록을 볼 수 있는 home으로 이동
    if request.method == 'POST':
        article = Article.objects.get(pk=article_pk)
        article.delete()
        return redirect('mtv:index')

web_day7_rev/templates/mtv/detail.html
{% include 'base.html' %}

{% block content %}

<h1>상세내용은 아래를 참고하세요</h1>
<h1>{{article.subject}}</h1>

<p>

    <strong>
        {{article.description}}
    </strong>

<div>

    <a href="{% url 'mtv:edit' article.pk %}">
        <button>
            수정
        </button>
        
    </a>


    <form action="{% url 'mtv:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <button>
            삭제
        </button>

    </form>
</div>
{% endblock content %}

web_day7_rev/templates/mtv/edit.html
{% include 'base.html' %}

{% block content %}
<h1>수정할 글</h1>
<form action="{% url 'mtv:update' article.pk%}" method="POST">
    {% csrf_token %}
    <div>
        <label for="subject">제목:</label>
        <input type="title" name='subject' type='text' value="{{article.subject}}">
    
    </div>
    
    <div>
        <label for="description">내용:</label>
        <textarea name="description" id="description" cols="30" rows="10">{{article.description}}</textarea>
    </div>
    
    <div>
        <input type="submit" value="수정">
    </div>
</form>

{% endblock content %}

web_day7_rev/templates/mtv/index.html
{% include 'base.html' %}

{% block content %}

<h1>글 목록</h1>
{% for article in articles %}

<li><a href="{% url 'mtv:detail' article.pk %}">{{article.subject}}</a></li>

{% endfor %}

{% endblock content %}

web_day7_rev/templates/mtv/new.html
{% include 'base.html' %}

{% block content %}

<h1>New Article</h1>

<form action="{% url 'mtv:create' %}" method="POST">
{% csrf_token %}
<div>
    <label for="subject">제목:</label>
    <input type="title" name='subject' type='text'>

</div>

<div>
    <label for="description">내용:</label>
    <textarea name="description" id="description" cols="30" rows="10"></textarea>
</div>

<div>
    <input type="submit" value="제출">
</div>

</form>
{% endblock content %}